<?php
return [
    'detail'=>[
        
            'id'=>[
                'name'=>'id',
                'tip'=>'',
                'type'=>'text',
            ],
            'key'=>[
                'name'=>'key',
                'tip'=>'',
                'type'=>'text',
            ],
            'cat'=>[
                'name'=>'分类',
                'tip'=>'',
                'type'=>'text',
            ],
            'type'=>[
                'name'=>'类型',
                'tip'=>'',
                'type'=>'text',
            ],
            'value'=>[
                'name'=>'分类',
                'tip'=>'',
                'type'=>'text',
            ],
            'created_at'=>[
                'name'=>'created_at',
                'tip'=>'',
                'type'=>'timestamp',
            ],
            'updated_at'=>[
                'name'=>'updated_at',
                'tip'=>'',
                'type'=>'timestamp',
            ],
    ],
];