<?php
/**
 * Larfree Api类
 * @author blues
 */
namespace App\Http\Controllers\Api\Test;
use App\Exceptions\ApiException;
use App\Models\Test\TestTest;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Larfree\Controllers\ApisController as Controller;
use App\Jobs\SendReminderEmail;
use Log;
use Larfree\Responses\ApiResponse;
class TestController extends Controller
{

    public $in=[
        'index'=>[

        ],
        'update'=>[
            '*',
            'datetime'=>[
                'name'=>'日期',
                'rule'=>['required','date'],
            ],
            'select'=>[
                'rule'=>['required'],
            ],
            'title3',
        ],
        'store'=>[
            '*',
            'datetime'=>[
                'name'=>'日期',
                'rule'=>['required','date'],
            ],
            'select'=>[
                'rule'=>['required'],
            ],
            'title3'=>false,
        ]
    ];


    public function __construct(TestTest $model)
    {
        $this->model = $model;
        parent::__construct();
    }


    /**
     * 假设是项目中的一个API
     * @SWG\Get(path="/test/{id}",
     *   tags={"tags测试","测试2"},
     *   summary="简介",
     *   description="请求该接口需要先登录。",
     *   produces={"application/json"},
     *   @SWG\Response(response="default", description="操作成功"),
     *   @SWG\Response(
     *     response=200,
     *     description="A list with products",
     *   ),
     *   @SWG\Response(
     *     response="403",
     *     description="an ""unexpected"" error",
     *   ),
     *   security={{
     *     "Authorization":{}
     *   }}
     * )
     */
    public function index(Request $request)
    {
        dump($request->all());
//        $data = parent::index($request);
//        $data = $this->model->link()->take(2)->get();
//        return Response()->success($data,'成功',['cat'=>['name'=>'123']]);
        return parent::index($request);
    }

    /**
     * 假设是项目中的一个API
     *
     * @SWG\Post(path="/test/{id}",
     *   tags={"tags测试"},
     *   summary="简介",
     *   description="请求该接口需要先登录。",
     *   produces={"application/json"},
     *     @SWG\Parameter(
     *         name="title",
     *         in="query",
     *         description="描述",
     *         required=true,
     *         type="integer",
     *         collectionFormat="multi"
     *     ),
     *   @SWG\Response(response="default", description="操作成功"),
     *   @SWG\Response(
     *     response=200,
     *     description="A list with products",
     *   ),
     *   @SWG\Response(
     *     response="403",
     *     description="an ""unexpected"" error"
     *   ),
     *    security={{
     *     "Authorization":{}
     *   }}
     * )
     */
    public function store(Request $request)
    {
        return parent::store($request); // TODO: Change the autogenerated stub
    }
}